# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f63a855e6f81e29394dbb15eb94eefe900b2a9f46ae64606c2b21b4c025c39142f7c71a843dd90f455f0d56cccfe81bbc8384777776eeafe63d8fe66e85132ca

test:
  secret_key_base: d839d99cc8d2ef43154069170f6f51048e5e3092d688f6f1c667bc8bd797b6cb3277657f124c8c251ffc7d6dfa3bb3ceb2b3ff6ed816b66dd7a30da7a066f0e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
